insert into item (number, name, amount, inventory_code,deposit,withdrawal) values (1,'extra bag', 10, 'bag-001',0,0);
insert into item (number, name, amount, inventory_code,deposit,withdrawal) values (2,'vanilla shirt', 15, 'shirt-003',0,0);
insert into item (number, name, amount, inventory_code,deposit,withdrawal) values (3,'3d blanket', 18, 'blanket-510',0,0);
insert into item (number, name, amount, inventory_code,deposit,withdrawal) values (4,'microfiber socket', 12, 'socket-064',0,0);
insert into item (number, name, amount, inventory_code,deposit,withdrawal) values (5,'mama shoes', 34, 'shoe-021',0,0);
insert into item (number, name, amount, inventory_code,deposit,withdrawal) values (6,'Almond ', 34, 'food-021',0,0);
insert into item (number, name, amount, inventory_code,deposit,withdrawal) values (7,'Alpen ', 34, 'food-022',0,0);
insert into item (number, name, amount, inventory_code,deposit,withdrawal) values (8,'Sugar ', 34, 'food-023',0,0);
insert into item (number, name, amount, inventory_code,deposit,withdrawal) values (9,'Apple', 34, 'food-024',0,0);
insert into item (number, name, amount, inventory_code,deposit,withdrawal) values (10,'Apple Jacks', 34, 'food-025',0,0);
insert into item (number, name, amount, inventory_code,deposit,withdrawal) values (11,'Raisin ', 34, 'food-026',0,0);
insert into item (number, name, amount, inventory_code,deposit,withdrawal) values (12,'Peanut', 34, 'food-027',0,0);
insert into item (number, name, amount, inventory_code,deposit,withdrawal) values (13,'Oats', 34, 'food-028',0,0);
insert into item (number, name, amount, inventory_code,deposit,withdrawal) values (14,'Caramel', 34, 'food-029',0,0);
insert into item (number, name, amount, inventory_code,deposit,withdrawal) values (15,'Grain', 34, 'food-030',0,0);
insert into item (number, name, amount, inventory_code,deposit,withdrawal) values (16,'Banana ', 34, 'food-031',0,0);
insert into item (number, name, amount, inventory_code,deposit,withdrawal) values (17,'Nut', 34, 'food-032',0,0);
insert into item (number, name, amount, inventory_code,deposit,withdrawal) values (18,'Berry', 34, 'food-033',0,0);
insert into item (number, name, amount, inventory_code,deposit,withdrawal) values (19,'Cheerios', 34, 'food-034',0,0);
insert into item (number, name, amount, inventory_code,deposit,withdrawal) values (20,'Chocolate', 34, 'food-035',0,0);
insert into item (number, name, amount, inventory_code,deposit,withdrawal) values (21,'MultiGrain', 34, 'food-036',0,0);
insert into item (number, name, amount, inventory_code,deposit,withdrawal) values (22,'Pumpkin', 34, 'food-037',0,0);
insert into item (number, name, amount, inventory_code,deposit,withdrawal) values (23,'Strawberry', 34, 'food-038',0,0);
insert into item (number, name, amount, inventory_code,deposit,withdrawal) values (24,'Yogurt', 34, 'food-039',0,0);
insert into item (number, name, amount, inventory_code,deposit,withdrawal) values (25,'Corn', 34, 'food-040',0,0);
insert into item (number, name, amount, inventory_code,deposit,withdrawal) values (26,'Honey Nut', 34, 'food-041',0,0);
insert into item (number, name, amount, inventory_code,deposit,withdrawal) values (27,'Rice', 34, 'food-042',0,0);
insert into item (number, name, amount, inventory_code,deposit,withdrawal) values (28,'Wheat', 34, 'food-043',0,0);
insert into item (number, name, amount, inventory_code,deposit,withdrawal) values (29,'Choco', 34, 'food-044',0,0);
insert into item (number, name, amount, inventory_code,deposit,withdrawal) values (30,'Cookie', 34, 'food-045',0,0);
insert into item (number, name, amount, inventory_code,deposit,withdrawal) values (31,'mama Cookie', 34, 'food-046',5,22);
update hibernate_sequences set next_val=31;
